name: Example workflow for Python using Flint AI Inventory Scan
on: push
jobs:
  security:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@master
      - name: Run Flint AI Inventory detection
        uses: sandbox-quantum/aispm-inventory-action@main
        with:
          flintai_instance: https://app.flintai.dev
          flintai_token: ${{ secrets.FLINTAI_TOKEN }}
          llm_model: anthropic:claude-opus-4-8
          llm_api_key: ${{ secrets.LLM_API_KEY }}
